package com.soodalbbobgi.app.core.theme

import androidx.compose.runtime.Immutable
import androidx.compose.runtime.staticCompositionLocalOf
import androidx.compose.ui.graphics.Brush
import androidx.compose.ui.graphics.Color

@Immutable
data class SoodalColors(
    val bgDeep: Color,
    val bgBase: Color,
    val surface1: Color,
    val surface2: Color,
    val surface3: Color,
    val glassBg: Color,
    val glassBorder: Color,
    val accentBlue: Color,
    val accentBlueSoft: Color,
    val accentPurple: Color,
    val accentPurpleSoft: Color,
    val accentGold: Color,
    val accentGoldSoft: Color,
    val success: Color,
    val warn: Color,
    val textPrimary: Color,
    val textSecondary: Color,
    val textTertiary: Color,
    val gradBlue: Brush,
    val gradGold: Brush,
    val gradPurple: Brush,
    val gradCard: Brush,
    /** 화면 전체 배경 — 물빛 파스텔 그라데이션(디자인 v3.0). 모든 화면 바닥. */
    val screenBg: Brush,
    val glowBlue: Color,
    val glowGold: Color,
    val glowPurple: Color,
    val tabbarBg: Color,
    val tabbarBorder: Color,
    val cardBg: Color,
    val cardBorder: Color,
    val cardShadow: Color,
    val inputBg: Color,
    val inputBorder: Color,
    val inputPlaceholder: Color,
    val btnPrimaryText: Color,
    val btnGoldText: Color,
    val btnPurpleText: Color,
    val isDark: Boolean,
)

val LocalSoodalColors = staticCompositionLocalOf<SoodalColors> {
    error("No SoodalColors provided. Wrap your composable in SoodalTheme.")
}

private fun gradientBrush(colors: List<Color>) = Brush.linearGradient(
    colors = colors,
)

val LightColors = SoodalColors(
    bgDeep = Color(0xFFEEF3F8), bgBase = Color(0xFFE4EBF4),
    surface1 = Color(0xFFFFFFFF), surface2 = Color(0xFFF7FAFD), surface3 = Color(0xFFE8EEF7),
    glassBg = Color.White.copy(alpha = 0.74f),
    glassBorder = Color.White.copy(alpha = 0.90f),
    accentBlue = Color(0xFF2D86C4), accentBlueSoft = Color(0xFF6FC0EC).copy(alpha = 0.18f),
    accentPurple = Color(0xFF6E55C9), accentPurpleSoft = Color(0xFFA793EC).copy(alpha = 0.16f),
    accentGold = Color(0xFFC8910F), accentGoldSoft = Color(0xFFF6C95B).copy(alpha = 0.18f),
    success = Color(0xFF1E9E78), warn = Color(0xFFD9614A),
    textPrimary = Color(0xFF1A2438), textSecondary = Color(0xFF5C6B7E), textTertiary = Color(0xFFA7B0BF),
    gradBlue = gradientBrush(listOf(Color(0xFF89CEF0), Color(0xFF5AAFD8))),
    gradGold = gradientBrush(listOf(Color(0xFFFAD878), Color(0xFFEFB43A))),
    gradPurple = gradientBrush(listOf(Color(0xFFBBA7F0), Color(0xFF8572D8))),
    gradCard = gradientBrush(listOf(Color(0xFFCFE9FA), Color(0xFFD6F0E6), Color(0xFFE4DCF8))),
    screenBg = Brush.verticalGradient(listOf(Color(0xFFCFE9FA), Color(0xFFD6F0E6), Color(0xFFE4DCF8))),
    glowBlue = Color(0xFF2D86C4).copy(alpha = 0.16f),
    glowGold = Color(0xFFC8910F).copy(alpha = 0.18f),
    glowPurple = Color(0xFF6E55C9).copy(alpha = 0.18f),
    tabbarBg = Color.White.copy(alpha = 0.86f),
    tabbarBorder = Color.White.copy(alpha = 0.90f),
    // 글래스: 카드도 반투명 프로스트 — 물빛 배경이 비쳐 글래스로 읽힌다. 흰색 좀더 태움.
    cardBg = Color.White.copy(alpha = 0.74f), cardBorder = Color.White.copy(alpha = 0.90f),
    cardShadow = Color(0xFF1E3C64).copy(alpha = 0.10f),
    inputBg = Color(0xFFFFFFFF), inputBorder = Color(0xFF1E3C64).copy(alpha = 0.12f),
    inputPlaceholder = Color(0xFFB8C0CC),
    btnPrimaryText = Color.White, btnGoldText = Color.White, btnPurpleText = Color.White,
    isDark = false,
)

val NeonColors = SoodalColors(
    bgDeep = Color(0xFF0A0E1A), bgBase = Color(0xFF0E1426),
    surface1 = Color(0xFF111827), surface2 = Color(0xFF1A2235), surface3 = Color(0xFF243049),
    glassBg = Color.White.copy(alpha = 0.06f),
    glassBorder = Color.White.copy(alpha = 0.12f),
    accentBlue = Color(0xFF00F5FF), accentBlueSoft = Color(0xFF00F5FF).copy(alpha = 0.14f),
    accentPurple = Color(0xFFBF5AF2), accentPurpleSoft = Color(0xFFBF5AF2).copy(alpha = 0.16f),
    accentGold = Color(0xFFFFD60A), accentGoldSoft = Color(0xFFFFD60A).copy(alpha = 0.18f),
    success = Color(0xFF30D158), warn = Color(0xFFFF6B6B),
    textPrimary = Color(0xFFE8EAF6), textSecondary = Color(0xFF8892A4), textTertiary = Color(0xFF4A5568),
    gradBlue = gradientBrush(listOf(Color(0xFF00F5FF), Color(0xFF4FB8FF))),
    gradGold = gradientBrush(listOf(Color(0xFFFFE66B), Color(0xFFFFB02E))),
    gradPurple = gradientBrush(listOf(Color(0xFFC679FF), Color(0xFF7C4DFF))),
    gradCard = gradientBrush(listOf(Color(0xFF0D1A30), Color(0xFF0A1520), Color(0xFF0D1030))),
    screenBg = Brush.verticalGradient(listOf(Color(0xFF0E1A30), Color(0xFF06080F))),
    glowBlue = Color(0xFF00F5FF).copy(alpha = 0.18f),
    glowGold = Color(0xFFFFD60A).copy(alpha = 0.22f),
    glowPurple = Color(0xFFBF5AF2).copy(alpha = 0.22f),
    tabbarBg = Color(0xFF0A0E1A).copy(alpha = 0.85f),
    tabbarBorder = Color.White.copy(alpha = 0.12f),
    cardBg = Color(0xFF1A2235), cardBorder = Color.White.copy(alpha = 0.05f),
    cardShadow = Color.Transparent,
    inputBg = Color(0xFF111827), inputBorder = Color.White.copy(alpha = 0.12f),
    inputPlaceholder = Color(0xFF4A5568),
    btnPrimaryText = Color(0xFF001821), btnGoldText = Color(0xFF3A2400), btnPurpleText = Color(0xFF1B0035),
    isDark = true,
)

val CalmColors = SoodalColors(
    bgDeep = Color(0xFF11151C), bgBase = Color(0xFF161B25),
    surface1 = Color(0xFF1A2030), surface2 = Color(0xFF232A3D), surface3 = Color(0xFF243049),
    glassBg = Color.White.copy(alpha = 0.06f),
    glassBorder = Color.White.copy(alpha = 0.12f),
    accentBlue = Color(0xFF6EE0E6), accentBlueSoft = Color(0xFF6EE0E6).copy(alpha = 0.14f),
    accentPurple = Color(0xFFB19BE8), accentPurpleSoft = Color(0xFFB19BE8).copy(alpha = 0.16f),
    accentGold = Color(0xFFF2C94C), accentGoldSoft = Color(0xFFF2C94C).copy(alpha = 0.18f),
    success = Color(0xFF30D158), warn = Color(0xFFFF6B6B),
    textPrimary = Color(0xFFE8EAF6), textSecondary = Color(0xFF8892A4), textTertiary = Color(0xFF4A5568),
    gradBlue = gradientBrush(listOf(Color(0xFFA6EEF2), Color(0xFF6EE0E6))),
    gradGold = gradientBrush(listOf(Color(0xFFF2C94C), Color(0xFFD4A030))),
    gradPurple = gradientBrush(listOf(Color(0xFFB19BE8), Color(0xFF8E70D0))),
    gradCard = gradientBrush(listOf(Color(0xFF1A2433), Color(0xFF161D2A), Color(0xFF1C1D35))),
    screenBg = Brush.verticalGradient(listOf(Color(0xFF11151C), Color(0xFF0C0F15))),
    glowBlue = Color(0xFF6EE0E6).copy(alpha = 0.16f),
    glowGold = Color(0xFFF2C94C).copy(alpha = 0.18f),
    glowPurple = Color(0xFFB19BE8).copy(alpha = 0.18f),
    tabbarBg = Color(0xFF0A0E1A).copy(alpha = 0.85f),
    tabbarBorder = Color.White.copy(alpha = 0.12f),
    cardBg = Color(0xFF232A3D), cardBorder = Color.White.copy(alpha = 0.05f),
    cardShadow = Color.Transparent,
    inputBg = Color(0xFF1A2030), inputBorder = Color.White.copy(alpha = 0.12f),
    inputPlaceholder = Color(0xFF4A5568),
    btnPrimaryText = Color(0xFF001821), btnGoldText = Color(0xFF3A2400), btnPurpleText = Color(0xFF1B0035),
    isDark = true,
)

val PastelColors = SoodalColors(
    bgDeep = Color(0xFF1A1A2E), bgBase = Color(0xFF221F3A),
    surface1 = Color(0xFF2A2746), surface2 = Color(0xFF322F54), surface3 = Color(0xFF3D3A66),
    glassBg = Color.White.copy(alpha = 0.06f),
    glassBorder = Color.White.copy(alpha = 0.12f),
    accentBlue = Color(0xFF8EE6F2), accentBlueSoft = Color(0xFF8EE6F2).copy(alpha = 0.14f),
    accentPurple = Color(0xFFD6A3FF), accentPurpleSoft = Color(0xFFD6A3FF).copy(alpha = 0.16f),
    accentGold = Color(0xFFFFD8A8), accentGoldSoft = Color(0xFFFFD8A8).copy(alpha = 0.18f),
    success = Color(0xFF30D158), warn = Color(0xFFFF6B6B),
    textPrimary = Color(0xFFF0EBFF), textSecondary = Color(0xFF8892A4), textTertiary = Color(0xFF4A5568),
    gradBlue = gradientBrush(listOf(Color(0xFFBFF3FA), Color(0xFF8EE6F2))),
    gradGold = gradientBrush(listOf(Color(0xFFFFD8A8), Color(0xFFE0B080))),
    gradPurple = gradientBrush(listOf(Color(0xFFD6A3FF), Color(0xFFB080E8))),
    gradCard = gradientBrush(listOf(Color(0xFF2D2A4D), Color(0xFF2A2849), Color(0xFF322A4D))),
    screenBg = Brush.verticalGradient(listOf(Color(0xFF1A1A2E), Color(0xFF141425))),
    glowBlue = Color(0xFF8EE6F2).copy(alpha = 0.22f),
    glowGold = Color(0xFFFFD8A8).copy(alpha = 0.25f),
    glowPurple = Color(0xFFD6A3FF).copy(alpha = 0.25f),
    tabbarBg = Color(0xFF0A0E1A).copy(alpha = 0.85f),
    tabbarBorder = Color.White.copy(alpha = 0.12f),
    cardBg = Color(0xFF322F54), cardBorder = Color.White.copy(alpha = 0.05f),
    cardShadow = Color.Transparent,
    inputBg = Color(0xFF2A2746), inputBorder = Color.White.copy(alpha = 0.12f),
    inputPlaceholder = Color(0xFF4A5568),
    btnPrimaryText = Color(0xFF001821), btnGoldText = Color(0xFF3A2400), btnPurpleText = Color(0xFF1B0035),
    isDark = true,
)
